---
title: "FE620 Project"
author: "Andrew Finn"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ragtop)
```

```{r}
#S - Price of Stock at t=0
#sig - Volatility of Stock
#r - Risk-free Rate
#N - Number of steps in total
#t - Time to Expiry
#cp - Call or put
#K - Strike
am_price_tree <- function(S,sig,r,N,t,cp,K) {
  
  #Calculate U, D and P-Star
  U<-exp(sig*sqrt(t/N))
  D<-exp(-sig*sqrt(t/N))
  p<-(exp(r*(t/N))-D)/(U-D)
  
  #Create stock price tree
  tree <- matrix(0, nrow=N+1, ncol=N+1)
  for (i in 1:((N)+1)) {
    for (j in 1:i) {
      tree[j, i] <- S * (U)^(i-j) * (D)^(j-1)
    }  
  }
  
  opt_tree <- matrix(0, nrow=N+1, ncol=N+1)
  #if call do
  if(cp=="c"){
    #Calculate value at last day
    for(x in c(1:(N+1))){
      opt_tree[x, (N)+1] <- max(tree[x, N+1]-K,0)
    }
    
    #Go back each step while comparing continuation value vs exercise value
    for (i in seq((N),1,-1)) {
      for (j in c(0:i)) {
        
        ex_now<-max(tree[j,i]-K,0)

        opt_tree[j, i] <- max(ex_now,(p*(opt_tree[j, i+1]) + (1-p) * (opt_tree[j+1, i+1]))*exp(r * (t/N)))
        
        }  
    }
    #Print Call Price
    #print("American Call Price: ")
    #print(opt_tree[1,1])
    }
  
  #if put do(same as call pretty much)
  else{
    for(x in c(0:(N)+1)){
      opt_tree[x, (N)+1] <- max(K-tree[x, N+1],0)
    }
    
    for (i in seq((N),1,-1)) {
      for (j in c(0:i)) {
        
        ex_now<-max(K-tree[j,i],0)
        
        opt_tree[j, i] <- max(ex_now,(p*(opt_tree[j, i+1]) + (1-p) * (opt_tree[j+1, i+1]))*exp(r * (t/N)))
        
      }  
    }
    #print("American Put Price: ")
    #print(opt_tree[1,1])
  }
  
  #Create Delta Tree and Calculate Delta
  delta_tree <- matrix(0, nrow=N, ncol=N)
  for (i in seq(1,N,1)) {
      for (j in c(1:i)) {
        delta_tree[j, i] <- (opt_tree[j,i+1]-opt_tree[j+1,i+1])/(tree[j,i+1]-tree[j+1,i+1])
      }  
    }
  
  
  #Output option price tree and delta tree
  #print("Option Price Tree: ")
  #print(opt_tree)
  
  #print("Delta Tree: ")
  #print(delta_tree)
  
  return(opt_tree[1,1])
    
}

am_price_tree(418,.25,.05,6,1,"c",415)

```

```{r}
#See convergence
prices<-c()

for(i in seq(1,252,2)){
  prices<-c(prices,am_price_tree(418,.25,.05,i,1,"c",415))
}


plot(prices)
lines(prices)
```


```{r}
#Get Option Data
opt_data<-read.csv("/Users/andrew/Documents/SCHOOL/2023/yahoo_options.csv")

#Separate Calls and Puts
calls<-opt_data[opt_data$Type == "calls",]
puts<-opt_data[opt_data$Type == "puts",]

#Data Clean
calls<-calls[order(calls$tau,calls$strike),]
puts<-puts[order(puts$tau,puts$strike),]

opt_table <- data.frame(matrix(ncol = 5, nrow = 0))

for(i in c(1:length(puts$lastTradeDate))){
  
  if(puts$strike[i] %in% calls[calls$tau==puts$tau[i],15]){
    
    opt_table<-rbind(opt_table,c(puts$tau[i], puts$strike[i], calls[(calls$tau==puts$tau[i] & calls$strike == puts$strike[i]),4], puts$bid[i], puts$Spot[i]))
    
  }
}

colnames(opt_table) <- c('tau', 'X', 'C_t', 'P_t', 'S_t')

#Apply our model using parameters from historical data
n<-length(opt_table$tau)
model_puts<-c()
model_calls<-c()

for(i in c(1:n)){
  S<-opt_table$S_t[i]
  v<-.25
  rf<-.05
  steps<-round(252*opt_table$tau[i])
  time<-opt_table$tau[i]
  strike<-opt_table$X[i]
  
  model_puts<-c(model_puts,am_price_tree(S,v,rf,steps,time,"p",strike))
  model_calls<-c(model_calls,am_price_tree(S,v,rf,steps,time,"c",strike))
}

opt_table<-cbind(opt_table,model_calls,model_puts)


#Compare our prices to historical prices
plot(opt_table$C_t-opt_table$model_calls)

plot(opt_table$P_t-opt_table$model_puts)

```
